name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Validate Terraform for each environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ "dev", "prod" ]
    env:
      TF_IN_AUTOMATION: "true"
    defaults:
      run:
        working-directory: "environments/${{ matrix.environment }}"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ----------------------
      # Terraform Setup & Linting
      # ----------------------

      - name: Setup Terraform Cloud Credentials
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials": {"app.terraform.io": {"token": "${{ secrets.TFC_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.11.3"  # Update to a recent stable version

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      # ----------------------
      # Security Scans with tfsec
      # ----------------------
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .

      # ----------------------
      # Security Scans with Checkov
      # ----------------------
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          soft_fail: true
          download_external_modules: true
